#include <cygni/effects/effect.hpp>
#include <cygni/effects/shift.hpp>
#include <cygni/effects/zig.hpp>
#include <cygni/effects/stutter.hpp>
#include <cygni/effects/spin.hpp>
#include <cygni/effects/chase.hpp>
#include <cygni/effects/rain.hpp>
#include <cygni/effects/perseids.hpp>
#include <cygni/effects/cedar.hpp>
#include <cygni/effects/willow.hpp>
#include <cygni/effects/nightsky.hpp>
#include <cygni/effects/spectrum.hpp>
